FROM nginx:1.19.3-alpine
LABEL description="test_case_saraphan" \
      version="0.1" \
      maintainer="TheSuncatcher222" \
      deployer="https://github.com/TheSuncatcher222"
COPY nginx.conf /etc/nginx/templates/default.conf.template
